replace EDITOR with SECRET_EDITOR
EDITOR is likely to have unsafe defaults (writing cleartext secrets to
various places) and users wouldn’t want to change their usual EDITOR
just for editing secrets safely. It’s a different use case, it’s better
to use a different tool (and env var).

diff --git a/cmd/edit-team-secret b/cmd/edit-team-secret
--- a/cmd/edit-team-secret
+++ b/cmd/edit-team-secret
@@ -2,6 +2,21 @@
 
 set -euf -o pipefail
 
+# ${X:-Y} returns Y when X is undefined or empty.
+# We can’t just test -z ${X} because we set -u above for safety.
+if [[ -z ${SECRET_EDITOR:-} ]]; then
+    if command -v nano >/dev/null; then
+        SECRET_EDITOR="nano --restricted --saveonexit"  # easier for the uninitiated
+    elif command -v vi >/dev/null; then
+        # POSIX, so should be there. The options likely only work for vim,
+        # to which vi likely points on most modern systems.
+        SECRET_EDITOR="vi -c 'set viminfo= | set noswapfile noundofile nobackup'"
+    else
+        echo 1>&2 "Error: SECRET_EDITOR not set, and neither nano nor vi available."
+        exit 1
+    fi
+fi
+
 DIR="$(cd $(dirname "$0")/.. && pwd)"
 
 TMP_FILE=$(mktemp)
@@ -17,6 +32,6 @@ function cleanup()
 # make sure the decrypted file is deleted
 trap cleanup EXIT
 
-$EDITOR $TMP_FILE
+$SECRET_EDITOR $TMP_FILE
 
 "$DIR"/cmd/upsert-team-secret "$1" <$TMP_FILE
